        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 27 13:18:05 2014
        MODULE FNCLOSEFILES__genmod
          INTERFACE 
            SUBROUTINE FNCLOSEFILES
            END SUBROUTINE FNCLOSEFILES
          END INTERFACE 
        END MODULE FNCLOSEFILES__genmod
