        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 27 13:18:02 2014
        MODULE FNCNTBAND__genmod
          INTERFACE 
            SUBROUTINE FNCNTBAND
            END SUBROUTINE FNCNTBAND
          END INTERFACE 
        END MODULE FNCNTBAND__genmod
