        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 27 13:17:56 2014
        MODULE FNDIELECTRIC__genmod
          INTERFACE 
            SUBROUTINE FNDIELECTRIC
            END SUBROUTINE FNDIELECTRIC
          END INTERFACE 
        END MODULE FNDIELECTRIC__genmod
