        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 27 13:17:51 2014
        MODULE FNEXCITONDISPERSION__genmod
          INTERFACE 
            SUBROUTINE FNEXCITONDISPERSION
            END SUBROUTINE FNEXCITONDISPERSION
          END INTERFACE 
        END MODULE FNEXCITONDISPERSION__genmod
