        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 27 13:18:26 2014
        MODULE FNEXCITONENERGY__genmod
          INTERFACE 
            SUBROUTINE FNEXCITONENERGY(EF_MIN,IKCM)
              REAL(KIND=8) :: EF_MIN
              INTEGER(KIND=4) :: IKCM
            END SUBROUTINE FNEXCITONENERGY
          END INTERFACE 
        END MODULE FNEXCITONENERGY__genmod
