        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 27 13:18:09 2014
        MODULE FNGEOMPROP__genmod
          INTERFACE 
            SUBROUTINE FNGEOMPROP
            END SUBROUTINE FNGEOMPROP
          END INTERFACE 
        END MODULE FNGEOMPROP__genmod
