        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 27 13:17:49 2014
        MODULE FNGRAPHENEENERGY__genmod
          INTERFACE 
            SUBROUTINE FNGRAPHENEENERGY(E,CC,CV,K)
              REAL(KIND=8) :: E(2)
              COMPLEX(KIND=8) :: CC(2)
              COMPLEX(KIND=8) :: CV(2)
              REAL(KIND=8) :: K(2)
            END SUBROUTINE FNGRAPHENEENERGY
          END INTERFACE 
        END MODULE FNGRAPHENEENERGY__genmod
