        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 27 13:17:58 2014
        MODULE FNINPUT__genmod
          INTERFACE 
            SUBROUTINE FNINPUT
            END SUBROUTINE FNINPUT
          END INTERFACE 
        END MODULE FNINPUT__genmod
