        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 27 13:18:04 2014
        MODULE FNOPENFILES__genmod
          INTERFACE 
            SUBROUTINE FNOPENFILES
            END SUBROUTINE FNOPENFILES
          END INTERFACE 
        END MODULE FNOPENFILES__genmod
