        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 27 13:17:53 2014
        MODULE FNPHYSCONST__genmod
          INTERFACE 
            SUBROUTINE FNPHYSCONST
            END SUBROUTINE FNPHYSCONST
          END INTERFACE 
        END MODULE FNPHYSCONST__genmod
