        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 27 13:18:07 2014
        MODULE FNSAVESIMINFO__genmod
          INTERFACE 
            SUBROUTINE FNSAVESIMINFO
            END SUBROUTINE FNSAVESIMINFO
          END INTERFACE 
        END MODULE FNSAVESIMINFO__genmod
