        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 27 13:17:47 2014
        MODULE FNSELFENERGY__genmod
          INTERFACE 
            SUBROUTINE FNSELFENERGY
            END SUBROUTINE FNSELFENERGY
          END INTERFACE 
        END MODULE FNSELFENERGY__genmod
